# Config file for automatic testing at travis-ci.org

language: python

sudo: required

services:
  - xvfb

python:
    - 3.7

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda install --yes python=3.7;
  - conda update --yes conda
  - export PYTHONPATH=$PWD/dioptas:$PYTHONPATH

  #start x-server
  - export DISPLAY=:99.0

addons:
  apt:
    packages:
      - gfortran
      - libgfortran3

install:
    - conda install --yes pycifrw pandas python-dateutil h5py scikit-image future qtpy pyfai lmfit mock pytest pytest-cov pyqtgraph -c cprescher
    - pip install pyepics

    - cd dioptas/model/util/
    - f2py -c -m smooth_bruckner smooth_bruckner.f95
    - cd ../../../

script:
    - py.test dioptas/tests/unit_tests
    - py.test dioptas/tests/controller_tests
    - py.test dioptas/tests/functional_tests
