# This is a basic workflow to help you get started with Actions

name: BUILD

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_unix:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.7
        channels: cprescher
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Install Conda Dependencies
      shell: bash -l {0}
      run: conda install --yes pycifrw pandas python-dateutil h5py scikit-image future qtpy pyfai lmfit mock pytest pytest-cov pyqtgraph cython
        
    - name: Install Pip Dependencies
      shell: bash -l {0}
      run: pip install pyepics extra_data pyinstaller
        
    - name: Run PyInstaller
      shell: bash -l {0}
      run: bash create_executable.sh

    - name: Run Dioptas
      shell: bash -l {0}
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd dist/Dioptas*
        xvfb-run ./Dioptas test

    - name: Run Dioptas
      shell: bash -l {0}
      if: matrix.os == 'macos-latest'
      run: |
        cd dist/Dioptas*
        pwd
        ls
        ./run_dioptas test
